# giới hạn bộ nhớ tối đa trên RAM
maxmemory 256mb

# Least recently used: khi bộ nhớ đạt tới 256Mb, Redis sẽ tự động xóa các khóa có thời gian sống (TTL)(time to live: thời gian sống của 1 key tính bằng giây)
# đã được thiết lập và ít được sử dụng nhất để giải phóng bộ nhớ cho các khóa mới.
maxmemory-policy volatile-lru

# bật persistence để lưu dữ liệu vào đĩa
# Redis hỗ trợ hai phương pháp persistence: RDB (Redis Database) và AOF (Append Only File).
# RDB tạo ra một snapshot của dữ liệu tại một thời điểm cụ thể, trong khi AOF ghi lại tất cả các lệnh thay đổi dữ liệu vào một file log, cho phép phục hồi dữ liệu gần như hoàn chỉnh.
# Trong trường hợp này, chúng ta sẽ sử dụng RDB để lưu dữ liệu định kỳ
save 900 1 # lưu dữ liệu sau mỗi 900 giây nếu có ít nhất 1 key đã thay đổi
save 300 10 # lưu dữ liệu sau mỗi 300 giây nếu có ít nhất 10 key đã thay đổi
save 60 10000 # lưu dữ liệu sau mỗi 60 giây nếu có ít nhất 10000 key đã thay đổi

dir /data